# Generated by Django 5.0.2 on 2024-02-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
