# Generated by Django 5.0.2 on 2024-02-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('core', '0005_pontoturistico_endereco'),
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(blank=True, null=True, to='atracoes.atracao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, to='comentarios.comentario'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
        ),
    ]
