# Generated by Django 5.0.2 on 2024-07-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='atracao',
            new_name='atracoes',
        ),
    ]
